version: '2'
services:
  server:
    build: server
    ports:
     - "80:8080"
    depends_on:
     - redis
  redis:
    image: redis
    command: redis-server /data/redis.conf
    volumes:
     - ./data:/data
