version: '2'
services:
  server:
    build: server
    ports:
     - "80:8080"
    volumes:
     - ./server:/var/app
    depends_on:
     - mongo
  mongo:
    image: mongo
    volumes:
     - ./data:/data/db