version: '2'
    services:
      server:
        build: server
        ports:
         - "80:8080"
        volumes:
         - server:/var/app
        depends_on:
         - mango
      mango:
        image: mango
        volumes:
         - data:/data/db