- name: update repositories cache and install vlc
  apt:
    name: vlc
    update_cache: yes
- name: copy alsa usb sound driver conf
  copy: src=files/alsa_usb.conf dest=/usr/share/alsa/alsa.conf.d/
- name: copy agent
  copy: src=../agent/fangge-agent.py dest=/usr/local/bin/ mode="u+rwx,g+rx,o+rx"
- name: enable agent on boot clean
  replace: dest=/etc/rc.local regexp='^runuser.*' 
- name: enable agent on boot
  replace: dest=/etc/rc.local regexp='^exit 0' replace='runuser -l pi -c \'fangge-agent.py --url "{{ AGENT_URL }}" --id {{ AGENT_ID }} --token {{ AGENT_TOKEN }} --path {{ MUSIC_FOLDER }} --info "{{ AGENT_INFO }}"\'\nexit 0' backup=yes
- name: mkdir music data
  file: path={{ MUSIC_FOLDER }} state=directory mode="u+rw,g+rwx,o+rwx"
  become: no
- name: copy a sample mp3
  copy: src=../agent/Music/aller.mp3 dest={{ MUSIC_FOLDER }}
  become: no